<?php

namespace frontend\controllers\base;
/**
 * @Created by PhpStorm.
 * @Desc: 基础控制器
 * @Author: panyuting
 * @Date: 2016/11/24
 * @Time: 15:53
 */

use yii\web\Controller;

class BaseController extends Controller{

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}